name: Deploy Homelab

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy stacks
        run: |
          cd ~/docker/homelab
          git pull origin main
          cd plex
          docker compose pull
          docker compose up -d
          cd ../monitoring
          docker compose pull
          docker compose up -d
